name: make_everything_ok
description: A new Flutter project.
publish_to: "none"
version: 1.0.21+3

environment:
  sdk: ">=3.1.0-262.2.beta <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  lottie: ^2.6.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
